- .trivyignore
- README.md
- helm_deploy/hmpps-dpr-tools-api/values.yaml
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/config/DigitalPrisonReportingExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/config/ToolsApiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/controller/DefinitionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/exception/InvalidDefinitionException.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/service/DefinitionService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/integration/ReportDefinitionIntegrationTest.kt
- src/test/resources/application-test.yml
- Endpoint name tweak.
- Role update.
- Reduce replicas (fixes issues with in-memory caching).
- Validate definition maps successfully (dataset/field reference verification).
> [DPR2-198] Definition verification and numerous small tweaks

- build.gradle.kts
reporting-lib:3.0.0 -> reporting-lib:3.0.1
> bump version

- build.gradle.kts
Updated lib version to fix the 500 NPE when the rows contain null values and there are formulas.
> DPR2-341 updated lib to fix NPE error

- build.gradle.kts
> DPR2-413 updated lib version

- build.gradle.kts
Updated tools with the latest changes of the library related to "visible" and "mandatory".
> DPR2-413 bump lib version

- build.gradle.kts
Updated lib to rename CTE stages.
> DPR2-427 bump lib version

- build.gradle.kts
Changes to include display dataset fallback.
> DPR2-267 bump lib version

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/controller/DefinitionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/service/DefinitionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/service/FakeConfiguredApiService.kt
Library update to support filter queries from different datasets.
This includes a change to validate using the actual map function which is used by the main API.
> DPR2-796 bump lib version

- build.gradle.kts
Update backend lib to latest version.
> DPR2-761 update lib to latest

- build.gradle.kts
Library version upgrade to fix issue with filter validation for filters coming from parameters.
> DPR2-980 updated lib version

- build.gradle.kts
Update library to support context_ CTE.
> DPR2-996 library update

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-test.yaml
- src/main/resources/application.yml
Revert to the previous library version before the workgroup changes.
> Dpr2 945 revert to previous lib version

- build.gradle.kts
Update lib to hide prompt empty columns from reports.
> DPR2-1039 update lib

- build.gradle.kts
> no-jira update lib version

- build.gradle.kts
Updated lib with the new dashboard definition changes.
This also removes the existing metrics endpoints.
> DPR2-1433 library update

- build.gradle.kts
Library update to include all dashboard endpoints.
> DPR2-1391 library update

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/controller/DefinitionController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/data/InMemoryProductDefinitionRepository.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/service/DefinitionService.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/service/FakeConfiguredApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/integration/ReportDefinitionIntegrationTest.kt
Updated backend library and brought the code up to date with the lib changes.
> DPR2-1075 upgrade lib

- .circleci/config.yml
These changes fix the deployment by adding the missing step to persist to workspace.
> Dpr2 1645 Added persist to workspace step

- build.gradle.kts
Update lib based on these changes:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/528
> no_jira update lib

- helm_deploy/hmpps-dpr-tools-api/values.yaml
Activities datasource is failing to connect to the CP Postgress db and this is logging errors repeatedly.
These changes disable this datasource.
> no_jira - disable activities DS as it's failing to connect

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
> DPR2-1778 change host to call manage-users-api

- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingtoolsapi/config/RequestLoggerConfig.kt
With these changes the BE will log incoming HTTP requests which is very helpful when trying to investigate issues.
> DPR2-2166 log incoming requests
